### ISSUE TITLE
Validation errors with ESPHome 2024.3.1 and 2024.4.0-dev

### ISSUE THREAD

**Issue by mihsu81** [sammcj/esphome-esp-s3-box-3-volume#1]
Hi @sammcj,

Thank you for your great work.

I'm getting validation errors with ESPHome 2024.3.1 and 2024.4.0-dev even after the PR has been merged:

```ID 'speaker_volume' of type esp_box_volume::ESPBoxVolume doesn't inherit from output::FloatOutput. Please double check your ID is pointing to the correct value.```

![image](https://github.com/sammcj/esphome-esp-s3-box-3-volume/assets/40715497/6b8e6d27-4e2c-4ecf-bb7d-3e1bb5875a70)

Here's my config yaml:
```yaml
substitutions:
  name: esp32-s3-box-3-5ac364
  devicename: esp32_s3_box_3_5ac364
  friendly_name: ESP32 S3 Box 3 5ac364
  micro_wake_word_model: alexa
  wake_word_text: "Alexa"
  starting_up: "Pornire..."
  wake_word_prompt: "Spune \\\"Alexa\\\""
  listening_prompt: "Cum te pot ajuta?"
  error_prompt: "Scuze. A fost intâmpinată o eroare."

external_components:
  - source: github://sammcj/esphome-esp-s3-box-3-volume@main
    components: [esp_box_volume]
    refresh: always

packages:
  esphome.voice-assistant: github://esphome/firmware/wake-word-voice-assistant/esp32-s3-box-3.yaml@main
#  esphome.voice-assistant: github://jaymunro/esphome_firmware/wake-word-voice-assistant/esp32-s3-box-3.yaml@continued-conversation
#  esphome.voice-assistant: github://esphome/firmware/voice-assistant/esp32-s3-box-3.yaml@main

esphome:
  name: ${name}
  name_add_mac_suffix: false
  friendly_name: ${friendly_name}
  on_boot:
    then:
      - output.set_level:
          id: speaker_volume
          level: 0.85  # 85% volume_multiplier

voice_assistant:
  volume_multiplier: 3.0

esp_box_volume:
  id: speaker_volume

api:
  reboot_timeout: 1h
  encryption:
    key: !secret api_encryption_key

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

ota:
  safe_mode: true
  password: !secret ota_password

web_server:
  port: 80
  auth:
    username: !secret username
    password: !secret password
  include_internal: true

time:
  - platform: homeassistant
    id: homeassistant_time

mdns:
  disabled: false

binary_sensor:
  - platform: status
    name: Status

text_sensor:
  - platform: wifi_info
    ip_address:
      name: IP Address
    ssid:
      name: Connected SSID
    bssid:
      name: Connected BSSID
    mac_address:
      name: MAC Wifi Address

  - platform: version
    name: ESPHome Version

button:
  - platform: restart
    name: Restart
    id: ${devicename}_reset
    entity_category: diagnostic

  - platform: factory_reset
    name: Factory Reset
    id: ${devicename}_fatory_reset
    internal: true
    entity_category: diagnostic

  - platform: safe_mode
    name: Safe Mode Boot
    id: ${devicename}_safe_mode_boot
    entity_category: diagnostic

sensor:
  - platform: uptime
    name: Device Uptime
    id: ${devicename}_device_uptime

  - platform: wifi_signal
    name: Wifi Signal
    id: ${devicename}_wifi_signal
    update_interval: 60s

  - platform: internal_temperature
    name: Internal Temperature
    id: ${devicename}_internal_temperature
    update_interval: 60s

  - platform: template
    name: Free Memory
    icon: mdi:memory
    entity_category: diagnostic
    lambda: return heap_caps_get_free_size(MALLOC_CAP_INTERNAL) / 1024;
    unit_of_measurement: 'kB'
    state_class: measurement
```
